In [2]:
from Bio import SeqIO

with open("P02089.fasta") as file:
    for record in SeqIO.parse(file, "fasta"):
        print(record.id)

sp|P02089|HBB2_MOUSE


In [4]:
from Bio import SeqIO

for record in SeqIO.parse("P02089.fasta", "fasta"):
    print(record.seq)


MVHLTDAEKSAVSCLWAKVNPDEVGGEALGRLLVVYPWTQRYFDSFGDLSSASAIMGNPKVKAHGKKVITAFNEGLKNLDNLKGTFASLSELHCDKLHVDPENFRLLGNAIVIVLGHHLGKDFTPAAQAAFQKVVAGVATALAHKYH


In [9]:
record.seq

Seq('MVHLTDAEKSAVSCLWAKVNPDEVGGEALGRLLVVYPWTQRYFDSFGDLSSASA...KYH')

In [3]:
f = open("P02089.fasta", "r")
read = f.read()
print(read)

>sp|P02089|HBB2_MOUSE Hemoglobin subunit beta-2 OS=Mus musculus OX=10090 GN=Hbb-b2 PE=1 SV=2
MVHLTDAEKSAVSCLWAKVNPDEVGGEALGRLLVVYPWTQRYFDSFGDLSSASAIMGNPK
VKAHGKKVITAFNEGLKNLDNLKGTFASLSELHCDKLHVDPENFRLLGNAIVIVLGHHLG
KDFTPAAQAAFQKVVAGVATALAHKYH


In [8]:
f = open("P02089.fasta", "r")
read = f.read()
seq = ""
read = read.split("\n")
for i in read:
    if ">" not in i:
        seq+=i
        
print(seq)

MVHLTDAEKSAVSCLWAKVNPDEVGGEALGRLLVVYPWTQRYFDSFGDLSSASAIMGNPKVKAHGKKVITAFNEGLKNLDNLKGTFASLSELHCDKLHVDPENFRLLGNAIVIVLGHHLGKDFTPAAQAAFQKVVAGVATALAHKYH


Dotplot


In [10]:
import numpy as np

f = open("P02089.fasta", "r")
read = f.read()
seq1 = ""
read = read.split("\n")
for i in read:
    if ">" not in i:
        seq1+=i

f_human = open("P68871.fasta", "r")
read_human = f_human.read()
seq2 = ""
read_human = read_human.split("\n")
for i in read_human:
    if ">" not in i:
        seq2+=i   
        
dotplot = np.zeros((len(seq1),len(seq2)))
for i in range(len(seq1)):
    for j in range(len(seq2)):
        if seq1[i] == seq2[j]:
            dotplot[i,j] = 1
        else:
            dotplot[i,j] = 0
print(dotplot)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]]


In [11]:
from Bio import SeqIO
from urllib.error import HTTPError  # Importujemy wyjątek HTTPError

import requests
import numpy as np

def get_uniprot_sequence(uniprot_id):
    url = f"https://www.uniprot.org/uniprot/{uniprot_id}.fasta"
    try:
        response = requests.get(url)
        response.raise_for_status()  # Sprawdź, czy odpowiedź nie zawiera błędu HTTP
        fasta_data = response.text
        lines = fasta_data.split('\n')
        seq = ''.join(lines[1:])  # Pobierz sekwencję z linii 2 i dalej (pomiń nagłówek)
        return seq
    except requests.exceptions.HTTPError as e:
        print(f"Wystąpił błąd HTTP: {e}")
        return None
    except Exception as e:
        print(f"Wystąpił inny błąd: {e}")
        return None

def start():
    while True:
        print("Wybierz metodę wprowadzania sekwencji: plik FASTA(1) lub ID Uniprot(2)")
        choice = input()
        if choice == "1":
            print("Podaj nazwę pliku")
            name = input()
            seq = ""  # Inicjalizacja zmiennej seq
            try:
                with open(name, "r") as f:  # Użyj 'with' do otwarcia pliku, aby uniknąć zapominania o zamknięciu pliku
                    read = f.read()
                    read = read.split("\n")
                    for i in read:
                        if ">" not in i:
                            seq += i
            except IOError as e:
                print("Wystąpił wyjątek:", e)
            return seq
        elif choice == "2":
            print("Podaj ID Uniprot")
            uniprot_id = input()
            seq = get_uniprot_sequence(uniprot_id)
            if seq:
                return seq
            else:
                print("Nie udało się pobrać sekwencji dla podanego ID Uniprot.")
        else:
            print("Błędna opcja")

start()

Wybierz metodę wprowadzania sekwencji: plik FASTA(1) lub ID Uniprot(2)
Podaj ID Uniprot


'MVHLTDAEKSAVSCLWAKVNPDEVGGEALGRLLVVYPWTQRYFDSFGDLSSASAIMGNPKVKAHGKKVITAFNEGLKNLDNLKGTFASLSELHCDKLHVDPENFRLLGNAIVIVLGHHLGKDFTPAAQAAFQKVVAGVATALAHKYH'

In [16]:
import numpy as np

class Sequence:
    def __init__(self, seq):
        self.sequence = seq
        self.length = len(seq)
        
    def __str__(self):
        return self.sequence
    
    def get_length(self):
        return self.length
    
    def dotplot(self, seq2):
        dp = np.zeros((self.length, seq2.get_length()))
        for i in range(self.length):
            for j in range(seq2.get_length()):
                if self.sequence[i] == seq2.sequence[j]:
                    dp[i,j] = 1
                else:
                    dp[i,j] = 0
        return dp


In [17]:
import requests
import numpy as np

def get_uniprot_sequence(uniprot_id):
    url = f"https://www.uniprot.org/uniprot/{uniprot_id}.fasta"
    try:
        response = requests.get(url)
        response.raise_for_status()  # Sprawdź, czy odpowiedź nie zawiera błędu HTTP
        fasta_data = response.text
        lines = fasta_data.split('\n')
        seq = ''.join(lines[1:])  # Pobierz sekwencję z linii 2 i dalej (pomiń nagłówek)
        return seq
    except requests.exceptions.HTTPError as e:
        print(f"Wystąpił błąd HTTP: {e}")
        return None
    except Exception as e:
        print(f"Wystąpił inny błąd: {e}")
        return None

def start():
    while True:
        print("Wybierz metodę wprowadzania sekwencji: plik FASTA(1) lub ID Uniprot(2)")
        choice = input()
        if choice == "1":
            print("Podaj nazwę pliku")
            name = input()
            seq = ""  # Inicjalizacja zmiennej seq
            try:
                with open(name, "r") as f:  # Użyj 'with' do otwarcia pliku, aby uniknąć zapominania o zamknięciu pliku
                    read = f.read()
                    read = read.split("\n")
                    for i in read:
                        if ">" not in i:
                            seq += i
            except IOError as e:
                print("Wystąpił wyjątek:", e)
            return seq
        elif choice == "2":
            print("Podaj ID Uniprot")
            uniprot_id = input()
            seq = get_uniprot_sequence(uniprot_id)
            if seq:
                return seq
            else:
                print("Nie udało się pobrać sekwencji dla podanego ID Uniprot.")
        else:
            print("Błędna opcja")

print("Wybierz pierwszą sekwencję:")
seq1 = Sequence(start())
print("Wybierz drugą sekwencję:")
seq2 = Sequence(start())
dp = seq1.dotplot(seq2)
print(dp)

Wybierz pierwszą sekwencję:
Wybierz metodę wprowadzania sekwencji: plik FASTA(1) lub ID Uniprot(2)
Podaj nazwę pliku
Wybierz drugą sekwencję:
Wybierz metodę wprowadzania sekwencji: plik FASTA(1) lub ID Uniprot(2)
Podaj nazwę pliku
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]]
